### PR TITLE
Revert "Develop to master"

### PR DESCRIPTION
**Pull request by ThrawnCA**
Reverts qld-gov-au/ckanext-data-qld-theme#149

### CODE REVIEW

**Comment by ThrawnCA** [comment]
The build failure is because we're reverting the compatibility fix; shouldn't be a problem in Staging since we'll re-merge before then.

**Comment by ThrawnCA** [comment]
Note that Staging data requests failed today due to the theme being merged without supporting extension updates.

**Comment by duttonw** [comment]
since it is using develop, it is a good sign that it is not compatible with latest extensions so rollback needs to also include previous tagged versions also

**Comment by ThrawnCA** [comment]
Tagged versions of ckanext-data-qld and ckanext-datarequests in the `requirements-dev.txt` file? Yes, that might be a good idea.

**Pull request merged**
